services:
  frontend:
    container_name: frontend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    tty: true
    restart: always
    volumes:
      - ./frontend:/frontend
      - frontend_node_modules:/frontend/node_modules
    depends_on:
      - backend
    extra_hosts:
      - "host.docker.internal:host-gateway"

  backend:
    build:
      context: ./backend
    container_name: backend
    volumes:
      - backend-data:/tmp
      - ./backend:/backend
    ports:
      - 8000:8000
    tty: true
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      db:
        condition: service_healthy

  database:
    container_name: database
    build:
      context: ./database
    volumes:
      - db-data:/var/lib/mysql
    command: mysqld --collation-server=utf8mb4_0900_bin --transaction-isolation=READ-COMMITTED
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - 53306:3306
    healthcheck:
     test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
     timeout: 5s
     retries: 1

volumes:
  db-data:

    